services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"

  postgres:
    container_name: postgress
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - log_destination=stderr
      - logging_collector=on
    ports:
      - "5432:5432"