name: Run tests on any Push event
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run Docker Compose
        run: docker compose -f docker-compose.yaml build
      -
        run: docker compose up -d
      - name: Check Docker container
        run: sleep 10
      -
        run: docker ps -a
      -
        run: docker compose logs
      - name: Test Docker Start
        run: curl http://127.0.0.1:8000
      -
        run: curl http://localhost:8000/unique_notes
      - uses: actions/setup-python@v1
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: coverage run -m pytest tests/test_application.py
      - name: Tests report
        run: coverage report
      - name: Start test Code with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./app"
          version: "~= 22.0"