name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

#      - name: Build and push Docker images
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: user/repo:latest

      - name: Run Docker Compose
        run: docker-compose up -d



        #  run_tests:
#    runs-on: [ubuntu-latest]
#    steps:
      # Чекаутим код
#      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
#      - uses: actions/setup-python@v1
#        with:
#          python-version: '3.12'
#          architecture: 'x64'
#      - name: Install requirements
        # Устанавливаем зависимости
#        run: pip install -r requirements.txt
#      - name: Run tests
#        run: coverage run -m pytest
#      - name: Tests report
#        run: coverage report
