name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-compose up
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: docker-compose up -d
    - name: Check running containers
      run: docker-compose ps -a
    - name: Check logs
      run: docker-compose logs app
    - name: Test with pytest
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: docker-compose exec app pytest
#  run_tests:
#    runs-on: [ubuntu-latest]
#    steps:
      # Чекаутим код
#      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
#      - uses: actions/setup-python@v1
#        with:
#          python-version: '3.12'
#          architecture: 'x64'
#      - name: Install requirements
        # Устанавливаем зависимости
#        run: pip install -r requirements.txt
#      - name: Run tests
#        run: coverage run -m pytest
#      - name: Tests report
#        run: coverage report
