name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      – name: Checkout repository
        uses: actions/checkout@master

      – name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      – name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      – name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      – name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      – name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache
          docker-compose -f docker-compose.yml push

      – name: Start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d

      – name: Run tests
        run: |
          # Добавьте ваши команды для тестирования здесь
          echo "Running tests..."

      – name: Stop and remove Docker Compose services
        run: |
          docker-compose -f docker-compose.yml down

#  run_tests:
#    runs-on: [ubuntu-latest]
#    steps:
      # Чекаутим код
#      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
#      - uses: actions/setup-python@v1
#        with:
#          python-version: '3.12'
#          architecture: 'x64'
#      - name: Install requirements
        # Устанавливаем зависимости
#        run: pip install -r requirements.txt
#      - name: Run tests
#        run: coverage run -m pytest
#      - name: Tests report
#        run: coverage report
