name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Run Docker Compose Action
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "test-container"
          test-command: "npm test"
#  run_tests:
#    runs-on: [ubuntu-latest]
#    steps:
      # Чекаутим код
#      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
#      - uses: actions/setup-python@v1
#        with:
#          python-version: '3.12'
#          architecture: 'x64'
#      - name: Install requirements
        # Устанавливаем зависимости
#        run: pip install -r requirements.txt
#      - name: Run tests
#        run: coverage run -m pytest
#      - name: Tests report
#        run: coverage report
